/**
 * Authoritative Data Source Configuration & Priorities
 */

import { SourceDefinition } from '@/types/sources';

export const DATA_SOURCES: readonly SourceDefinition[] = [
  // Mandatory Paid Media Sources
  {
    source_id: 'src-meta-ads',
    display_name: 'Meta Ad Library (Facebook & Instagram)',
    channel: 'Paid Media',
    platform: 'Meta',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'directly_available',
    crawler_strategy: 'Apify Meta Ad Library Actor with Thailand country filter',
    enabled: true,
  },
  {
    source_id: 'src-google-ads',
    display_name: 'Google Ads Transparency Center',
    channel: 'Paid Media',
    platform: 'Google Ads',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'partially_available',
    crawler_strategy: 'Targeted advertiser ID lookups for HP, Epson, Canon, Brother in Thailand',
    enabled: true,
  },

  // Mandatory Brand-Owned Social Sources
  {
    source_id: 'src-facebook-th',
    display_name: 'Official Thailand Brand Facebook Pages',
    channel: 'Social',
    platform: 'Facebook',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'directly_available',
    crawler_strategy: 'Targeted brand page feed crawling (HP, Epson, Canon, Brother TH)',
    enabled: true,
  },
  {
    source_id: 'src-instagram-th',
    display_name: 'Official Thailand Brand Instagram Accounts',
    channel: 'Social',
    platform: 'Instagram',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'directly_available',
    crawler_strategy: 'Official brand handle post extraction (@hpthailand, @epsonthailand, etc.)',
    enabled: true,
  },
  {
    source_id: 'src-youtube-th',
    display_name: 'Official Thailand Brand YouTube Channels',
    channel: 'Social',
    platform: 'YouTube',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'directly_available',
    crawler_strategy: 'Official brand channel video upload and engagement tracking',
    enabled: true,
  },

  // Mandatory E-Commerce Sources
  {
    source_id: 'src-shopee-th',
    display_name: 'Shopee Thailand (Official Mall & Top IT Dealers)',
    channel: 'E-commerce',
    platform: 'Shopee',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'reconstructable',
    crawler_strategy: 'Targeted official brand mall store and Ink Tank category extraction',
    enabled: true,
  },
  {
    source_id: 'src-lazada-th',
    display_name: 'Lazada Thailand (LazMall Flagships)',
    channel: 'E-commerce',
    platform: 'Lazada',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'reconstructable',
    crawler_strategy: 'LazMall flagship store catalog and promotion monitoring',
    enabled: true,
  },
  {
    source_id: 'src-tiktok-shop-th',
    display_name: 'TikTok Shop Thailand',
    channel: 'E-commerce',
    platform: 'TikTok Shop',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'current_only',
    crawler_strategy: 'Social-commerce promo and live flash sales snapshot capture',
    enabled: true,
  },
  {
    source_id: 'src-jib-th',
    display_name: 'JIB Thailand Specialist IT Retailer',
    channel: 'E-commerce',
    platform: 'JIB',
    priority: 'mandatory',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'directly_available',
    crawler_strategy: 'Specialist IT printer tank category scraping and price tracking',
    enabled: true,
  },

  // Secondary Sources
  {
    source_id: 'src-tiktok-brand-th',
    display_name: 'Official Brand TikTok Accounts (TH)',
    channel: 'Social',
    platform: 'TikTok',
    priority: 'secondary',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'partially_available',
    crawler_strategy: 'Official brand short-form video monitoring',
    enabled: true,
  },
  {
    source_id: 'src-linkedin-th',
    display_name: 'Official Brand LinkedIn Accounts (TH)',
    channel: 'Social',
    platform: 'LinkedIn',
    priority: 'secondary',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'partially_available',
    crawler_strategy: 'Brand page corporate announcement monitoring',
    enabled: false,
  },
  {
    source_id: 'src-advice-th',
    display_name: 'Advice Thailand',
    channel: 'E-commerce',
    platform: 'Advice',
    priority: 'secondary',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'partially_available',
    crawler_strategy: 'Secondary IT retailer price and stock check',
    enabled: false,
  },
  {
    source_id: 'src-powerbuy-th',
    display_name: 'Power Buy Thailand',
    channel: 'E-commerce',
    platform: 'Power Buy',
    priority: 'secondary',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: 'THB',
    historical_capability: 'partially_available',
    crawler_strategy: 'Retail chain catalog price check',
    enabled: false,
  },
  {
    source_id: 'src-youtube-ads',
    display_name: 'YouTube Video Ad Crawling',
    channel: 'Paid Media',
    platform: 'YouTube',
    priority: 'secondary',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'partially_available',
    crawler_strategy: 'Dedicated video ad monitoring',
    enabled: false,
  },

  // Dropped / Low Priority per Brief Section 9 Data Cut 5
  {
    source_id: 'src-consumer-forums',
    display_name: 'Thai Consumer Forums (Pantip, etc.)',
    channel: 'Consumer Review',
    platform: 'Facebook', // Placeholder platform
    priority: 'dropped',
    country: 'Thailand',
    language: 'th-TH',
    expected_currency: null,
    historical_capability: 'unavailable',
    crawler_strategy: 'General forum scraping (dropped due to low signal-to-noise ratio)',
    enabled: false,
  },
] as const;

export const MANDATORY_SOURCES = DATA_SOURCES.filter((s) => s.priority === 'mandatory');
export const SECONDARY_SOURCES = DATA_SOURCES.filter((s) => s.priority === 'secondary');
export const DROPPED_SOURCES = DATA_SOURCES.filter((s) => s.priority === 'dropped');
